db:
  image: mongo:3.0.2
scrapy:
  build: .
  command: scrapy crawl monumentParis
  volumes:
    - .:/projet1
  links:
    - db
frontend:
  build: .
  command: python -u app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/projet1
  links:
    - db
